### ISSUE TITLE
if (month) seems to fail for January

### ISSUE THREAD

**Issue by jtgasper3** [bbsimonbb/epoq#1]
https://github.com/bbsimonbb/epoq/blob/main/src/DateWithoutTime.ts#L5 seems falsy for January, producing bad DateWithoutTime data.

**Comment by bbsimonbb** [comment]
The idea of this package is to stay as close as possible to the Date object, which has zero-based months. I agree that this seems surprising, but I don't feel free to change this. Sorry to be so slow to comment, but I only saw this when the PR dropped. Oops.

**Comment by jtgasper3** [comment]
@bbsimonbb Please take another look. The if statement is broken if the month is January: `if (month)` might as well say `if (0) die!`

I don't think your conditional is working the way you think it is working... because it goes against what you just stated.

**Comment by jtgasper3** [comment]
This test will fail (I believe it will fail, but it has been a while since I re-wrote my code to work around the bug:

```javascript
it("Should be a 2023-01-01 ", () => {
    const myDate = new DateWithoutTime(2023, 0, 1);
   expect(myDate).toBeCorrect(); // Date is wrong
  });
